routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/user.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('user')->user();

    //dd($users);

    return view('user.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


  Route::group(['namespace' => 'Dashboard', 'middleware'=>['admin', 'admin.permissions'], 'prefix' => 'admin'], function() {
    Route::get('/', 'DashboardController@index');

    /************** Admin Account Settings */
    Route::get('/profile', 'DashboardController@profile');
    Route::post('/profile', 'DashboardController@save_profile');
    Route::get('/change_password', 'DashboardController@change_password');
    Route::post('/change_password', 'DashboardController@password_save');

    /************* Admins */
    Route::resource('admins', 'AdminController');
    Route::get('admins/edit_password/{id}', 'AdminController@change_password');
    Route::post('admins/save_password/{id}', 'AdminController@password_save');

    /************* Slider */
    Route::resource('slider', 'SliderController');

    /***** Web Pages Sections */
    Route::resource('sections', 'SectionController');

    /***** Categories */
    Route::resource('categories', 'CategoryController');

    /***** Categories Saller Services */
    Route::resource('saller/servcies/category', 'CategorySallerServciesController');

    /***** Galleries */
    Route::resource('galleries', 'GalleryController');
    Route::get('gallery_products/{id}', 'GalleryController@products');
    Route::get('gallery_orders/{id}', 'GalleryController@saller_orders');
    Route::get('gallery_products_favorite/{id}', 'GalleryController@productsFavorite');


    /*****  Saller Srvices */
    Route::resource('sallers/services', 'SallerServicesController');

    /***** Saller Codes */
    Route::resource('saller/codes', 'SallerCodeController');

    /***** Products */
    Route::resource('products', 'ProductController');
    Route::resource('/products_images', 'ProductImageController')->except(['create']);
    Route::get('/products_images/{id}/create', 'ProductImageController@create');
    Route::any('delete/product/color/{id}', 'ProductController@delete_product_color');
    Route::get('filter/subs/category', 'ProductController@filter_subs_category')->name('filter.subs.category');

    /***** cities & regions */
    Route::resource('cities', 'CityController');
    Route::resource('regions', 'RegionController');


    /***** Clients */
    Route::resource('clients', 'ClientController');
    Route::get('products_favorite/clients/{id}', 'ClientController@products_favorite');


    /***** Orders */
    Route::get('all/orders', 'OrderController@all_orders');
    Route::any('delete/order/{id}', 'OrderController@delete_order');

    // /******* Subscribers */
    // Route::get('sub/pending', 'SubscriberController@sub_pending');
    // Route::get('sub/finish', 'SubscriberController@sub_finish');
    // Route::get('sub/free/{id}', 'SubscriberController@sub_free');
    // Route::get('sub/payment/{id}', 'SubscriberController@sub_payment');
    // Route::get('sub/open/{id}', 'SubscriberController@sub_open');
    // Route::get('sub/block/{id}', 'SubscriberController@sub_block');

    /******* Social Media */
    Route::resource('social', 'SocialController');

    /*********** About Us */
    Route::resource('/about', 'AboutController');

    /*********** Sizes */
    Route::resource('/sizes', 'SizeController');

    /*********** colors */
    Route::resource('colors', 'ColorController');

    /****************** Contact Us */
    Route::get('/contact', 'ContactController@index');
    Route::post('/contact', 'ContactController@contact_save');

    /****************** Terms */
    Route::resource('terms', 'TermController');
    Route::get('user/terms', 'TermController@terms_user');

    /****************** Subscribers */
    Route::get('sub/pending', 'SubscriberController@sub_pending');
    Route::get('sub/finish', 'SubscriberController@sub_finish');

});


Route::get('/', 'AdminAuth\LoginController@showLoginForm')->name('login');
Route::group(['prefix' => 'admin'], function () {
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::get('/logout', 'AdminAuth\LoginController@logout')->name('logout');
});

app/Models/Gallery.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class Gallery extends Authenticatable
{

    use HasApiTokens, Notifiable;
    protected $fillable = [
      'activate_token', 'commercial_register', 'nationalist', 'password',
      'name_en', 'name_ar', 'phone', 'address_en', 'address_ar', 'map',
      'image', 'city_id', 'code', 'status', 'created_at', 'region_id', 'cat_id', 'sub_id',
      'instgram_link', 'facebook_link', 'twitter_link', 'youtube_link', 'whatsapp_link', 'mobile_link'
    ];
    
    protected $hidden = ['code', 'status', 'activate_token', 'password'];
    public function products()
    {
        return $this->hasMany('App\Models\Product', 'gallery_id', 'id');
    }

    public function sub()
    {
      return $this->hasOne('App\Models\Subscriber', 'saller_id', 'id');
    }

    public function city()
    {
      return $this->hasOne('App\Models\Region', 'city_id', 'id');
    }

    public function favorites()
    {
        return $this->hasMany('App\Models\ProductFavorite', 'saller_id', 'id');
    }

    public function review_saller()
    {
        return $this->hasMany('App\Models\RateSaller', 'saller_id', 'id');
    }
    
}

app/Http/Controllers/Dashboard/GalleryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use App\Models\ProductFavorite;
use App\Models\Gallery;
use App\Models\Order;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $galleries = Gallery::all();
        return view('admin.pages.galleries.index')->with(['galleries'=>$galleries]);
    }

    public function saller_orders($id)
    {
      $saller_orders = Order::whereHas('product', function($query) use($id){
            $query->where('gallery_id', $id);
        })->get();
        return view('admin.pages.galleries.orders')->with(['saller_orders' => $saller_orders]);
    }

    public function productsFavorite($id)
    {
        $products = ProductFavorite::where('saller_id', $id)->get();
        return view('admin.pages.galleries.products_favorite')->with(['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.galleries.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name_en'                     => 'required',
            'name_ar'                     => 'required',
            'phone'                       => 'required',
            'address_en'                  => 'required',
            'address_ar'                  => 'required',
            'map'                         => 'required',
            'image'                       => 'sometimes|nullable|image|mimes:jpeg,jpg,png',
            'commercial_register'         => 'sometimes|nullable|image|mimes:jpeg,jpg,png',
            'nationalist'                 => 'sometimes|nullable|image|mimes:jpeg,jpg,png',
            'instgram_link'               => 'nullable',
            'facebook_link'               => 'nullable',
            'twitter_link'                => 'nullable',
            'youtube_link'                => 'nullable'
        ],
        [
            'name_en.required'            => 'Please Enter Gallery Name (EN)',
            'name_ar.required'            => 'Please Enter Gallery Name (AR)',
            'phone.required'              => 'Please Enter Gallery Phone',
            'address_en.required'         => 'Please Enter Gallery Address (EN)',
            'address_ar.required'         => 'Please Enter Gallery Address (AR)',
            'map.required'                => 'Please Enter Gallery Map',
        ]);

        $gallery = new Gallery;
        $gallery->name_en  = $request->name_en;
        $gallery->name_ar  = $request->name_ar;
        $gallery->phone  = $request->phone;
        $gallery->address_en  = $request->address_en;
        $gallery->address_ar  = $request->address_ar;
        $gallery->map  = $request->map;


        if($request->has('image') && $request->image != null)
        {
          $image = $request->file('image');
          $imageName = time().'.'.$image->getClientOriginalExtension();
          $destinationPath = public_path('/uploads/galleries');
          $image->move($destinationPath, $imageName);
          $gallery->image ='/uploads/galleries/'.$imageName;
        }

        if($request->has('commercial_register') && $request->commercial_register != null)
        {
          $commercial_register = $request->file('commercial_register');
          $imageNameCommercial = time().'.'.$commercial_register->getClientOriginalExtension();
          $destinationPath = public_path('/uploads/galleries');
          $commercial_register->move($destinationPath, $imageNameCommercial);
          $gallery->commercial_register ='/uploads/galleries/'.$imageNameCommercial;
        }

        if($request->has('nationalist') && $request->nationalist != null)
        {
          $nationalist = $request->file('nationalist');
          $imageNameNationalist = time().'.'.$nationalist->getClientOriginalExtension();
          $destinationPath = public_path('/uploads/galleries');
          $image->move($destinationPath, $imageNameNationalist);
          $gallery->nationalist ='/uploads/galleries/'.$imageNameNationalist;
        }

        $gallery->instgram_link   = $request->instgram_link;
        $gallery->facebook_link   = $request->facebook_link;
        $gallery->twitter_link    = $request->twitter_link;
        $gallery->youtube_link    = $request->youtube_link;
        $gallery->save();

        alert()->success('تم الأضافة بنجاح');
        return redirect()->route('galleries.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $gallery = Gallery::findorfail($id);
        return view('admin.pages.galleries.edit', compact('gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $gallery = Gallery::findorfail($id);

        $validatedData = $request->validate([
            'name_en'                     => 'required',
            'name_ar'                     => 'required',
            'phone'                       => 'required',
            'address_en'                  => 'required',
            'address_ar'                  => 'required',
            'map'                         => 'required',
            'image'                       => 'sometimes|nullable|image|mimes:jpeg,jpg,png',
            'commercial_register'         => 'sometimes|nullable|image|mimes:jpeg,jpg,png',
            'nationalist'                 => 'sometimes|nullable|image|mimes:jpeg,jpg,png',
            'instgram_link'               => 'nullable',
            'facebook_link'               => 'nullable',
            'twitter_link'                => 'nullable',
            'youtube_link'                => 'nullable'
        ],
        [
            'name_en.required'            => 'Please Enter Gallery Name (EN)',
            'name_ar.required'            => 'Please Enter Gallery Name (AR)',
            'phone.required'              => 'Please Enter Gallery Phone',
            'address_en.required'         => 'Please Enter Gallery Address (EN)',
            'address_ar.required'         => 'Please Enter Gallery Address (AR)',
            'map.required'                => 'Please Enter Gallery Map',
        ]);
        $gallery->name_en  = $request->name_en;
        $gallery->name_ar  = $request->name_ar;
        $gallery->phone  = $request->phone;
        $gallery->address_en  = $request->address_en;
        $gallery->address_ar  = $request->address_ar;
        $gallery->map  = $request->map;

        if($request->hasFile('image'))
        {
            $validatedData = $request->validate([
                'image' => 'required|mimes:jpeg,png,jpg,gif,svg,webp'
            ],
            $messages = [
                'image.required' => 'Please Choose Image',
                'image.mimes' => 'Please Choose Valid Image File',
            ]);

            if (File::exists(public_path().$gallery->image))
            {
                File::delete(public_path().$gallery->image);
            }

            if (File::exists(public_path().$gallery->nationalist))
            {
                File::delete(public_path().$gallery->nationalist);
            }

            if (File::exists(public_path().$gallery->commercial_register))
            {
                File::delete(public_path().$gallery->commercial_register);
            }

            $image = $request->file('image');
            $imageName = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/uploads/galleries');
            $image->move($destinationPath, $imageName);
            $gallery->image = '/uploads/galleries/'.$imageName;
        }

        if($request->has('commercial_register') && $request->commercial_register != null)
        {
          $commercial_register = $request->file('commercial_register');
          $imageNameCommercial = time().'.'.$commercial_register->getClientOriginalExtension();
          $destinationPath = public_path('/uploads/galleries');
          $commercial_register->move($destinationPath, $imageNameCommercial);
          $gallery->commercial_register ='/uploads/galleries/'.$imageNameCommercial;
        }

        if($request->has('nationalist') && $request->nationalist != null)
        {
          $nationalist = $request->file('nationalist');
          $imageNameNationalist = time().'.'.$nationalist->getClientOriginalExtension();
          $destinationPath = public_path('/uploads/galleries');
          $image->move($destinationPath, $imageNameNationalist);
          $gallery->nationalist ='/uploads/galleries/'.$imageNameNationalist;
        }

        $gallery->instgram_link   = $request->instgram_link;
        $gallery->facebook_link   = $request->facebook_link;
        $gallery->twitter_link    = $request->twitter_link;
        $gallery->youtube_link    = $request->youtube_link;
        $gallery->save();

        alert()->success('تم التحديث بنجاح');
        return redirect()->route('galleries.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $gallery = Gallery::findorfail($id);

        if (File::exists(public_path().$gallery->image))
        {

resources/views/admin/pages/galleries/create.blade.php
@extends('admin.layout.main')
@section('content')
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fa fa-star"></i></span>
                <h3 class="kt-portlet__head-title"> &nbsp; أضافة تاجر </h3>
            </div>
        </div>
        <div class="kt-portlet__body">
			<form class="kt-form" method="post" action="{{url('admin/galleries')}}" enctype="multipart/form-data">
				{{csrf_field()}}

				<div class="form-group">
					<div class="row">
						<div class="col-md-12">
							<label>الأسم (EN)</label>
							<input class="form-control" type="text" placeholder="الأسم (EN)" name="name_en" value="{{old('name_en')}}" id="name_en" />
							@if ($errors->has('name_en'))<span class="form-text text-danger"><strong>{{ $errors->first('name_en') }}</strong></span>@endif
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="row">
						<div class="col-md-12">
							<label>الأسم (AR)</label>
							<input class="form-control" type="text" placeholder="الأسم (AR)" name="name_ar" value="{{old('name_ar')}}" id="name_ar" />
							@if ($errors->has('name_ar'))<span class="form-text text-danger"><strong>{{ $errors->first('name_ar') }}</strong></span>@endif
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="row">
						<div class="col-md-12">
							<label>الموبايل</label>
							<input class="form-control" type="text" placeholder="الموبايل" name="phone" value="{{old('phone')}}" id="phone" />
							@if ($errors->has('phone'))<span class="form-text text-danger"><strong>{{ $errors->first('phone') }}</strong></span>@endif
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="row">
						<div class="col-md-12">
							<label>العنوان (EN)</label>
							<input class="form-control" type="text" placeholder="العنوان (EN)" name="address_en" value="{{old('address_en')}}" id="address_en" />
							@if ($errors->has('address_en'))<span class="form-text text-danger"><strong>{{ $errors->first('address_en') }}</strong></span>@endif
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="row">
						<div class="col-md-12">
							<label>العنوان (AR)</label>
							<input class="form-control" type="text" placeholder="العنوان (AR)" name="address_ar" value="{{old('address_ar')}}" id="address_ar" />
							@if ($errors->has('address_ar'))<span class="form-text text-danger"><strong>{{ $errors->first('address_ar') }}</strong></span>@endif
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="row">
						<div class="col-md-12">
							<label>الخريطة</label>
							<input class="form-control" type="text" placeholder="الخريطة" name="map" value="{{old('map')}}" id="map" />
							@if ($errors->has('map'))<span class="form-text text-danger"><strong>{{ $errors->first('map') }}</strong></span>@endif
						</div>
					</div>
				</div>

        <div class="form-group">
					<div class="row">
						<div class="col-md-12">
							<label>كلمة السر</label>
							<input class="form-control" type="password" placeholder="كلمة السر" name="password" value="{{old('address_ar')}}" id="address_ar" />
							@if ($errors->has('password'))<span class="form-text text-danger"><strong>{{ $errors->first('password') }}</strong></span>@endif
						</div>
					</div>
				</div>

				<div class="form-group m-form__group row">
					<label class="col-lg-2 col-form-label">الصورة</label>
					<div class="col-lg-10">
						<div class="custom-file">
							<input type="file" class="custom-file-input" name="image" id="image" />
							<label class="custom-file-label" for="image">اختار الصورة</label>
						</div>
					</div>
				</div>

        <div class="form-group m-form__group row">
          <label class="col-lg-2 col-form-label">السجل التجاري</label>
          <div class="col-lg-10">
            <div class="custom-file">
              <input type="file" class="custom-file-input" name="commercial_register" id="image" />
              <label class="custom-file-label" for="image">اختار الصورة</label>
            </div>
          </div>
        </div>

        <div class="form-group m-form__group row">
          <label class="col-lg-2 col-form-label">البطاقة القومية</label>
          <div class="col-lg-10">
            <div class="custom-file">
              <input type="file" class="custom-file-input" name="nationalist" id="image" />
              <label class="custom-file-label" for="image">اختار الصورة</label>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <label>رابط الفيس بوك</label>
              <input class="form-control" type="text" placeholder="الفيسبوك" name="facebook_link" value="{{old('facebook_link')}}" id="phone" />
              @if ($errors->has('facebook_link'))<span class="form-text text-danger"><strong>{{ $errors->first('facebook_link') }}</strong></span>@endif
            </div>


            <div class="col-md-6">
              <label>رابط تويتر</label>
              <input class="form-control" type="text" placeholder="تويتر" name="twitter_link" value="{{old('twitter_link')}}" id="phone" />
              @if ($errors->has('twitter_link'))<span class="form-text text-danger"><strong>{{ $errors->first('twitter_link') }}</strong></span>@endif
            </div>

            <div class="col-md-6">
              <label>رابط الأنستجرام</label>
              <input class="form-control" type="text" placeholder="انتسجرام" name="instgram_link" value="{{old('instgram_link')}}" id="phone" />
              @if ($errors->has('instgram_link'))<span class="form-text text-danger"><strong>{{ $errors->first('instgram_link') }}</strong></span>@endif
            </div>


            <div class="col-md-6">
              <label>رابط اليوتيوب</label>
              <input class="form-control" type="text" placeholder="اليوتيوب" name="youtube_link" value="{{old('youtube_link')}}" id="phone" />
              @if ($errors->has('youtube_link'))<span class="form-text text-danger"><strong>{{ $errors->first('youtube_link') }}</strong></span>@endif
            </div>
          </div>
        </div>

				<div class="kt-portlet__foot">
					<div class="kt-form__actions text-right">
						<button type="submit" class="btn btn-success">حفظ</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/pages/galleries/products.blade.php
@extends('admin.layout.main')
@section('content')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fa fa-star"></i></span>
                <h3 class="kt-portlet__head-title">&nbsp; {{ $gallery->name_ar }} - المنتجات </h3>
            </div>

        </div>
        <div class="kt-portlet__body text-center">
			<table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
				<thead>
					<tr>
						<th>#</th>
						<th>الأسم (EN)</th>
						<th>الأسم (AR)</th>
						<th>القسم</th>
						<th>الأعدادات</th>
					</tr>
				</thead>
				<tbody>
					@foreach ($gallery->products as $product)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$product->title_en}}</td>
							<td>{{$product->title_ar}}</td>
							<td>{{$product->category['title_ar']}}</td>
							<td>
								<div class="dropdown">
									<button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
									aria-expanded="false">
										الأعدادات
									</button>
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<a class="dropdown-item" href="{{route('products.show', $product->id)}}">الصور</a>
									</div>
								</div>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
        </div>
	</div>
</div>
@endsection

resources/views/admin/pages/galleries/products_favorite.blade.php
@extends('admin.layout.main')
@section('content')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fas fa-boxes"></i></span>
                <h3 class="kt-portlet__head-title"> &nbsp; المنتجات المفضلة [{{$products->count()}}] منتج</h3>
            </div>

        </div>
        <div class="kt-portlet__body text-center">
			<table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
				<thead>
					<tr>
						<th>#</th>
						<th>الأسم (EN)</th>
						<th>الأسم (AR)</th>
						<th>القسم</th>
						<th>التاجر</th>
						<th>الأعدادات</th>
					</tr>
				</thead>
				<tbody>
					@foreach($products as $product)
             @if(App\Models\Product::where('id', $product->id)->count() > 0)
              @foreach(App\Models\Product::where('id', $product->product_id)->get() as $row)
  						<tr>
  							<td>{{$row->id}}</td>
  							<td>{{$row->title_en}}</td>
  							<td>{{$row->title_ar}}</td>
  							<td>{{(!empty($row->category)? $row->category->title_ar : '')}}</td>
  							<td>{{$row->gallery->name_en ?? ''}}</td>
  							<td>
  								<div class="dropdown">
  									<button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
  									aria-expanded="false">
  										الأعدادات
  									</button>
  									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
  										<a class="dropdown-item" href="{{route('products.show', $row->id)}}">الصور</a>
  									</div>
  								</div>
  							</td>
  						</tr>
              @endforeach
             @endif
					@endforeach
				</tbody>
			</table>
        </div>
	</div>
</div>
@endsection