routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/user.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('user')->user();

    //dd($users);

    return view('user.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


  Route::group(['namespace' => 'Dashboard', 'middleware'=>['admin', 'admin.permissions'], 'prefix' => 'admin'], function() {
    Route::get('/', 'DashboardController@index');

    /************** Admin Account Settings */
    Route::get('/profile', 'DashboardController@profile');
    Route::post('/profile', 'DashboardController@save_profile');
    Route::get('/change_password', 'DashboardController@change_password');
    Route::post('/change_password', 'DashboardController@password_save');

    /************* Admins */
    Route::resource('admins', 'AdminController');
    Route::get('admins/edit_password/{id}', 'AdminController@change_password');
    Route::post('admins/save_password/{id}', 'AdminController@password_save');

    /************* Slider */
    Route::resource('slider', 'SliderController');

    /***** Web Pages Sections */
    Route::resource('sections', 'SectionController');

    /***** Categories */
    Route::resource('categories', 'CategoryController');

    /***** Categories Saller Services */
    Route::resource('saller/servcies/category', 'CategorySallerServciesController');

    /***** Galleries */
    Route::resource('galleries', 'GalleryController');
    Route::get('gallery_products/{id}', 'GalleryController@products');
    Route::get('gallery_orders/{id}', 'GalleryController@saller_orders');
    Route::get('gallery_products_favorite/{id}', 'GalleryController@productsFavorite');


    /*****  Saller Srvices */
    Route::resource('sallers/services', 'SallerServicesController');

    /***** Saller Codes */
    Route::resource('saller/codes', 'SallerCodeController');

    /***** Products */
    Route::resource('products', 'ProductController');
    Route::resource('/products_images', 'ProductImageController')->except(['create']);
    Route::get('/products_images/{id}/create', 'ProductImageController@create');
    Route::any('delete/product/color/{id}', 'ProductController@delete_product_color');
    Route::get('filter/subs/category', 'ProductController@filter_subs_category')->name('filter.subs.category');

    /***** cities & regions */
    Route::resource('cities', 'CityController');
    Route::resource('regions', 'RegionController');


    /***** Clients */
    Route::resource('clients', 'ClientController');
    Route::get('products_favorite/clients/{id}', 'ClientController@products_favorite');


    /***** Orders */
    Route::get('all/orders', 'OrderController@all_orders');
    Route::any('delete/order/{id}', 'OrderController@delete_order');

    // /******* Subscribers */
    // Route::get('sub/pending', 'SubscriberController@sub_pending');
    // Route::get('sub/finish', 'SubscriberController@sub_finish');
    // Route::get('sub/free/{id}', 'SubscriberController@sub_free');
    // Route::get('sub/payment/{id}', 'SubscriberController@sub_payment');
    // Route::get('sub/open/{id}', 'SubscriberController@sub_open');
    // Route::get('sub/block/{id}', 'SubscriberController@sub_block');

    /******* Social Media */
    Route::resource('social', 'SocialController');

    /*********** About Us */
    Route::resource('/about', 'AboutController');

    /*********** Sizes */
    Route::resource('/sizes', 'SizeController');

    /*********** colors */
    Route::resource('colors', 'ColorController');

    /****************** Contact Us */
    Route::get('/contact', 'ContactController@index');
    Route::post('/contact', 'ContactController@contact_save');

    /****************** Terms */
    Route::resource('terms', 'TermController');
    Route::get('user/terms', 'TermController@terms_user');

    /****************** Subscribers */
    Route::get('sub/pending', 'SubscriberController@sub_pending');
    Route::get('sub/finish', 'SubscriberController@sub_finish');

});


Route::get('/', 'AdminAuth\LoginController@showLoginForm')->name('login');
Route::group(['prefix' => 'admin'], function () {
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::get('/logout', 'AdminAuth\LoginController@logout')->name('logout');
});

resources/views/admin/pages/categories_saller_servcies/create.blade.php
@extends('admin.layout.main')
@section('content')
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fas fa-list"></i></span>
                <h3 class="kt-portlet__head-title"> &nbsp; أضافة قسم رئيسي</h3>
            </div>
        </div>
        <div class="kt-portlet__body">
			<form class="kt-form" method="post" action="{{url('admin/saller/servcies/category')}}" enctype="multipart/form-data">
				{{csrf_field()}}
				<div class="form-group">
					<div class="row">
						<div class="col-md-4">
							<label>الأسم (EN)</label>
							<input class="form-control" type="text" placeholder="الأسم (EN)" name="name_en" value="{{old('name_en')}}" id="name_en" />
							@if ($errors->has('name_en'))<span class="form-text text-danger"><strong>{{ $errors->first('title_en') }}</strong></span>@endif
						</div>
						<div class="col-md-4">
							<label>الأسم (AR)</label>
							<input class="form-control" type="text" placeholder="الأسم (AR)" name="name_ar" value="{{old('name_ar')}}" id="name_ar" />
							@if ($errors->has('name_ar'))<span class="form-text text-danger"><strong>{{ $errors->first('name_ar') }}</strong></span>@endif
						</div>

						<div class="col-md-4">
							<label>صورة القسم</label>
							<input class="form-control" type="file" name="image">
							@if ($errors->has('image'))<span class="form-text text-danger"><strong>{{ $errors->first('image') }}</strong></span>@endif
						</div>
					</div>
				</div>

				<div class="kt-portlet__foot">
					<div class="kt-form__actions text-right">
						<button type="submit" class="btn btn-success">حفظ</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/pages/categories_saller_servcies/edit.blade.php
@extends('admin.layout.main')
@section('content')
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fas fa-list"></i></span>
                <h3 class="kt-portlet__head-title"> &nbsp; تعديل</h3>
            </div>
        </div>
        <div class="kt-portlet__body">
			<form class="kt-form" method="post" action="{{url('admin/saller/servcies/category/'.$category->id)}}" enctype="multipart/form-data">
				{{csrf_field()}}
				<input type="hidden" name="_method" value="PUT" />
				<div class="form-group">
					<div class="row">
						<div class="col-md-4">
							<label>الأسم (EN)</label>
							<input class="form-control" type="text" placeholder="الأسم (EN)" name="name_en" value="{{$category->name_en}}" id="name_en" />
							@if ($errors->has('name_en'))<span class="form-text text-danger"><strong>{{ $errors->first('name_en') }}</strong></span>@endif
						</div>
						<div class="col-md-4">
							<label>الأسم (AR)</label>
							<input class="form-control" type="text" placeholder="الأسم (AR)" name="name_ar" value="{{$category->name_ar}}" id="name_ar" />
							@if ($errors->has('name_ar'))<span class="form-text text-danger"><strong>{{ $errors->first('name_ar') }}</strong></span>@endif
						</div>

						<div class="col-md-4">
							<label>صورة القسم</label>
							<input class="form-control" type="file" name="image">
							@if ($errors->has('image'))<span class="form-text text-danger"><strong>{{ $errors->first('image') }}</strong></span>@endif
						</div>
					</div>
				</div>

				<div class="kt-portlet__foot">
					<div class="kt-form__actions text-right">
						<button type="submit" class="btn btn-success">حفظ</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/pages/categories_saller_servcies/index.blade.php
@extends('admin.layout.main')
@section('content')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fas fa-list"></i></span>
                <h3 class="kt-portlet__head-title"> &nbsp; أقسام الخدمات</h3>
            </div>
        </div>
        <div class="kt-portlet__body text-center">
			<table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
				<thead>
					<tr>
						<th>#</th>
						<th>اسم القسم (EN)</th>
						<th>اسم القسم (AR)</th>
						<th>الصورة</th>
						<th>الأعدادات</th>
					</tr>
				</thead>
				<tbody>
					@foreach ($categories as $categ)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>{{$categ->name_en}}</td>
							<td>{{$categ->name_ar}}</td>
							<td>
							@if(file_exists(public_path($categ->image)))
							<img src="{{asset($categ->image)}}" width="100px" height="100px">
							@else
							<h5 class="alert alert-danger text-center"> لا يوجد صورة </h5>
 							@endif
							</td>
							<td>
								<div class="dropdown">
									<button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
									aria-expanded="false">
										الأعدادات
									</button>
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<a class="dropdown-item" href="{{route('category.edit', $categ->id)}}"><i class="fas fa-edit"></i> تعديل</a>
										<a class="dropdown-item" data-toggle="modal" href="#myModal-{{ $categ->id }}"><i class="fas fa-trash"></i> حذف</a>
									</div>
								</div>

								<div class="modal fade" id="myModal-{{ $categ->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								<div class="modal-dialog">
								<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title">حذف القسم</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
								<form role="form" action="{{ url('admin/saller/servcies/category/'.$categ->id) }}" class="" method="POST">
								<input name="_method" type="hidden" value="DELETE">
								{{ csrf_field() }}
								<p>هل أنت متأكد من الحذف ؟</p>
								<button type="submit" class="btn btn-danger" name='delete_modal'>حذف</button>
								<button type="button" class="btn btn-success" data-dismiss="modal">اغلاق</button>
								</form>
								</div>
								</div>
								</div>
								</div>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
        </div>
	</div>
</div>
@endsection