routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/user.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('user')->user();

    //dd($users);

    return view('user.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


  Route::group(['namespace' => 'Dashboard', 'middleware'=>['admin', 'admin.permissions'], 'prefix' => 'admin'], function() {
    Route::get('/', 'DashboardController@index');

    /************** Admin Account Settings */
    Route::get('/profile', 'DashboardController@profile');
    Route::post('/profile', 'DashboardController@save_profile');
    Route::get('/change_password', 'DashboardController@change_password');
    Route::post('/change_password', 'DashboardController@password_save');

    /************* Admins */
    Route::resource('admins', 'AdminController');
    Route::get('admins/edit_password/{id}', 'AdminController@change_password');
    Route::post('admins/save_password/{id}', 'AdminController@password_save');

    /************* Slider */
    Route::resource('slider', 'SliderController');

    /***** Web Pages Sections */
    Route::resource('sections', 'SectionController');

    /***** Categories */
    Route::resource('categories', 'CategoryController');

    /***** Categories Saller Services */
    Route::resource('saller/servcies/category', 'CategorySallerServciesController');

    /***** Galleries */
    Route::resource('galleries', 'GalleryController');
    Route::get('gallery_products/{id}', 'GalleryController@products');
    Route::get('gallery_orders/{id}', 'GalleryController@saller_orders');
    Route::get('gallery_products_favorite/{id}', 'GalleryController@productsFavorite');


    /*****  Saller Srvices */
    Route::resource('sallers/services', 'SallerServicesController');

    /***** Saller Codes */
    Route::resource('saller/codes', 'SallerCodeController');

    /***** Products */
    Route::resource('products', 'ProductController');
    Route::resource('/products_images', 'ProductImageController')->except(['create']);
    Route::get('/products_images/{id}/create', 'ProductImageController@create');
    Route::any('delete/product/color/{id}', 'ProductController@delete_product_color');
    Route::get('filter/subs/category', 'ProductController@filter_subs_category')->name('filter.subs.category');

    /***** cities & regions */
    Route::resource('cities', 'CityController');
    Route::resource('regions', 'RegionController');


    /***** Clients */
    Route::resource('clients', 'ClientController');
    Route::get('products_favorite/clients/{id}', 'ClientController@products_favorite');


    /***** Orders */
    Route::get('all/orders', 'OrderController@all_orders');
    Route::any('delete/order/{id}', 'OrderController@delete_order');

    // /******* Subscribers */
    // Route::get('sub/pending', 'SubscriberController@sub_pending');
    // Route::get('sub/finish', 'SubscriberController@sub_finish');
    // Route::get('sub/free/{id}', 'SubscriberController@sub_free');
    // Route::get('sub/payment/{id}', 'SubscriberController@sub_payment');
    // Route::get('sub/open/{id}', 'SubscriberController@sub_open');
    // Route::get('sub/block/{id}', 'SubscriberController@sub_block');

    /******* Social Media */
    Route::resource('social', 'SocialController');

    /*********** About Us */
    Route::resource('/about', 'AboutController');

    /*********** Sizes */
    Route::resource('/sizes', 'SizeController');

    /*********** colors */
    Route::resource('colors', 'ColorController');

    /****************** Contact Us */
    Route::get('/contact', 'ContactController@index');
    Route::post('/contact', 'ContactController@contact_save');

    /****************** Terms */
    Route::resource('terms', 'TermController');
    Route::get('user/terms', 'TermController@terms_user');

    /****************** Subscribers */
    Route::get('sub/pending', 'SubscriberController@sub_pending');
    Route::get('sub/finish', 'SubscriberController@sub_finish');

});


Route::get('/', 'AdminAuth\LoginController@showLoginForm')->name('login');
Route::group(['prefix' => 'admin'], function () {
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::get('/logout', 'AdminAuth\LoginController@logout')->name('logout');
});

app/Models/Term.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Term extends Model
{
    protected $fillable = ['content_en', 'content_ar', 'type'];
}

app/Http/Controllers/API/TermController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Term;
use Validator;

class TermController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function terms_saller()
    {
        $terms_saller = Term::where('type', 'saller')->get();
        return response()->json(['status' => 'success', 'data' => $terms_saller]);
    }

    public function terms_user()
    {
        $terms_user = Term::where('type', 'user')->get();
        return response()->json(['status' => 'success', 'data' => $terms_user]);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'content_en' => 'required',
            'content_ar' => 'required',
            'type'       =>'required|in:saller,user'
        ],
        [
            'content_en.required'  => 'من فضلك أدخل المحتوي [EN]',
            'content_ar.required'  => 'من فضلك أدخل المحتوي [AR]',
            'type.required'        => 'من فضلك أدخل نوع الشروط و الأحكام',
            'type.in'              => 'يجب ان تكون نوع الشروط تاجر او عميل',
        ]);

        if ($validator->fails())
        {
            return response()->json(['status' => 'error','message' => 'Invalid Inputs','errors' => $validator->errors()]);
        }

        $term = new Term;
        $term->content_en  = $request->content_en;
        $term->content_ar  = $request->content_ar;
        $term->type  = $request->type;
        $term->save();
        return response()->json(['status' => 'success', 'data' => $term]);
    }

    public function edit(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'content_en' => 'required',
            'content_ar' => 'required',
            'type'       =>'required|in:saller,user'
        ],
        [
            'content_en.required'  => 'من فضلك أدخل المحتوي [EN]',
            'content_ar.required'  => 'من فضلك أدخل المحتوي [AR]',
            'type.required'        => 'من فضلك أدخل نوع الشروط و الأحكام',
            'type.in'              => 'يجب ان تكون نوع الشروط تاجر او عميل',
        ]);

        if ($validator->fails())
        {
            return response()->json(['status' => 'error','message' => 'Invalid Inputs','errors' => $validator->errors()]);
        }

        $term = Term::findorfail($request->id);
        $term->content_en  = $request->content_en;
        $term->content_ar  = $request->content_ar;
        $term->type  = $request->type;
        $term->save();
        return response()->json(['status' => 'success', 'data' => $term]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $term = Term::where('id', $request->id)->first();
        if($term)
        {
          $term->delete();
          return response()->json(['status' => 'success', 'messaage' => 'Deleted Done']);
        }else{
          return response()->json(['status' => 'success', 'message' => 'This Id Not Found In Database']);
        }

    }
}

app/Http/Controllers/Dashboard/TermController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Term;

class TermController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $terms_saller = Term::where('type', 'saller')->get();
        return view('admin.pages.terms.terms_saller')->with(['terms_saller' => $terms_saller]);
    }

    public function terms_user()
    {
        $terms_user = Term::where('type', 'user')->get();
        return view('admin.pages.terms.terms_user')->with(['terms_user' => $terms_user]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.terms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'content_en' => 'required',
            'content_ar' => 'required',
            'type'       =>'required|in:saller,user'
        ],
        [
            'content_en.required'  => 'من فضلك أدخل المحتوي [EN]',
            'content_ar.required'  => 'من فضلك أدخل المحتوي [AR]',
            'type.required'        => 'من فضلك أدخل نوع الشروط و الأحكام',
            'type.in'              => 'يجب ان تكون نوع الشروط تاجر او عميل',
        ]);

        $term = new Term;
        $term->content_en  = $request->content_en;
        $term->content_ar  = $request->content_ar;
        $term->type  = $request->type;
        $term->save();

        if($request->type == 'saller')
        {
          return redirect()->route('terms.index');
        }else{
          return redirect('admin/terms/user');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $term = Term::findorfail($id);
        return view('admin.pages.terms.edit')->with(['term' => $term]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validatedData = $request->validate([
            'content_en' => 'required',
            'content_ar' => 'required',
            'type'       =>'required|in:saller,user'
        ],
        [
            'content_en.required'  => 'من فضلك أدخل المحتوي [EN]',
            'content_ar.required'  => 'من فضلك أدخل المحتوي [AR]',
            'type.required'        => 'من فضلك أدخل نوع الشروط و الأحكام',
            'type.in'              => 'يجب ان تكون نوع الشروط تاجر او عميل',
        ]);

        $term = Term::findorfail($id);
        $term->content_en  = $request->content_en;
        $term->content_ar  = $request->content_ar;
        $term->type  = $request->type;
        $term->save();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $term = Term::findorfail($id);
        $term->delete();
        return back();
    }
}

resources/views/admin/pages/terms/create.blade.php
@extends('admin.layout.main')
@section('content')
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fas fa-bell"></i></span>
                <h3 class="kt-portlet__head-title"> أضافة شروط و أحكام</h3>
            </div>
        </div>
        <div class="kt-portlet__body">
			<form class="kt-form" method="post" action="{{route('terms.store')}}" enctype="multipart/form-data">
				{{csrf_field()}}
				<div class="form-group">
					<div class="row">
						<div class="col-md-12">
							<label> الشروط و الأحكام (AR)</label>
							<textarea class="form-control ckeditor" rows="7" name="content_ar"> </textarea>
							@if ($errors->has('content_ar'))<span class="form-text text-danger"><strong>{{ $errors->first('content_ar') }}</strong></span>@endif
						</div>

            <div class="col-md-12">
              <hr>
							<label>  الشروط و الأحكام (EN)</label>
							<textarea class="form-control ckeditor" rows="7" name="content_en"> </textarea>
							@if ($errors->has('content_en'))<span class="form-text text-danger"><strong>{{ $errors->first('content_en') }}</strong></span>@endif
						</div>

            <div class="col-md-12">
              <hr>
							<label>   تحديد اتجاه الشروط و الأحكام</label>
              <select class="form-control" name="type">
                  <option value="saller"> الي التاجر </option>
                  <option value="user"> الي العميل </option>
              </select>
							@if ($errors->has('type'))<span class="form-text text-danger"><strong>{{ $errors->first('type') }}</strong></span>@endif
						</div>
					</div>
				</div>
				<div class="kt-portlet__foot">
					<div class="kt-form__actions text-right">
						<button type="submit" class="btn btn-success">حفظ</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/pages/terms/edit.blade.php
@extends('admin.layout.main')
@section('content')
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fas fa-bell"></i></span>
                <h3 class="kt-portlet__head-title">Edit Status</h3>
            </div>
        </div>
        <div class="kt-portlet__body">
			<form class="kt-form" method="post" action="{{route('terms.update', $term->id)}}" enctype="multipart/form-data">
				{{csrf_field()}}
				<input type="hidden" name="_method" value="PUT" />
        <div class="form-group">
          <div class="row">
            <div class="col-md-12">
              <label> الشروط و الأحكام (AR)</label>
              <textarea class="form-control ckeditor" rows="7" name="content_ar">
                  {!! $term->content_ar !!}
              </textarea>
              @if ($errors->has('content_ar'))<span class="form-text text-danger"><strong>{{ $errors->first('content_ar') }}</strong></span>@endif
            </div>

            <div class="col-md-12">
              <hr>
              <label>  الشروط و الأحكام (EN)</label>
              <textarea class="form-control ckeditor" rows="7" name="content_en">
                    {!! $term->content_en !!}
              </textarea>
              @if ($errors->has('content_en'))<span class="form-text text-danger"><strong>{{ $errors->first('content_en') }}</strong></span>@endif
            </div>

            <div class="col-md-12">
              <hr>
              <label>   تحديد اتجاه الشروط و الأحكام</label>
              <select class="form-control" name="type">
                  <option value="saller" @if($term->type == 'saller') selected @endif> الي التاجر </option>
                  <option value="user" @if($term->type == 'user') selected @endif> الي العميل </option>
              </select>
              @if ($errors->has('type'))<span class="form-text text-danger"><strong>{{ $errors->first('type') }}</strong></span>@endif
            </div>
          </div>
        </div>
				<div class="kt-portlet__foot">
					<div class="kt-form__actions text-right">
						<button type="submit" class="btn btn-success">Save</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/pages/terms/terms_saller.blade.php
@extends('admin.layout.main')
@section('content')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fas fa-bell"></i></span>
                <h3 class="kt-portlet__head-title">الشروط و الأحكام للتاجر</h3>
            </div>
        </div>
        <div class="kt-portlet__body text-center">
			<table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
				<thead>
					<tr>
						<th>#</th>
						<th>الشروط و الأحكام (AR)</th>
            <th>الشروط و الأحكام(EN)</th>
						<th>الأعدادات</th>
					</tr>
				</thead>
				<tbody>
					@foreach($terms_saller as $term)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalar{{$term->id}}">
                   أضغط للقراءة
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModalar{{$term->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                         {!! $term->content_ar !!}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
              <td>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalen{{$term->id}}">
                   أضغط للقراءة
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModalen{{$term->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                         {!! $term->content_en !!}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
							<td>
								<div class="dropdown">
									<button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
									aria-expanded="false">
										الأعدادات
									</button>
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<a class="dropdown-item" href="{{route('terms.edit', $term->id)}}">تعديل</a>
										<a class="dropdown-item" data-toggle="modal" href="#myModal-{{ $term->id }}">حذف</a>
									</div>
								</div>

								<div class="modal fade" id="myModal-{{ $term->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								<div class="modal-dialog">
								<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title">حذف الشروط</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
								<form role="form" action="{{ url('admin/terms/'.$term->id) }}" class="" method="POST">
								<input name="_method" type="hidden" value="DELETE">
								{{ csrf_field() }}
								<p>هل أنت متأكد من الحذف ؟</p>
								<button type="submit" class="btn btn-danger" name='delete_modal'>حذف</button>
								<button type="button" class="btn btn-success" data-dismiss="modal">الغاء</button>
								</form>
								</div>
								</div>
								</div>
								</div>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
        </div>
	</div>
</div>
@endsection

resources/views/admin/pages/terms/terms_user.blade.php
@extends('admin.layout.main')
@section('content')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon"><i class="kt-font-brand fas fa-bell"></i></span>
                <h3 class="kt-portlet__head-title"> &nbsp; الشروط و الأحكام للعميل </h3>
            </div>
        </div>
        <div class="kt-portlet__body text-center">
			<table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
				<thead>
					<tr>
						<th>#</th>
						<th>الشروط و الأحكام (AR)</th>
            <th>الشروط و الأحكام(EN)</th>
						<th>الأعدادات</th>
					</tr>
				</thead>
				<tbody>
					@foreach($terms_user as $term)
						<tr>
							<td>{{$loop->iteration}}</td>
							<td>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalar{{$term->id}}">
                   أضغط للقراءة
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModalar{{$term->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                         {!! $term->content_ar !!}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
              <td>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalen{{$term->id}}">
                   أضغط للقراءة
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModalen{{$term->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                         {!! $term->content_en !!}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
							<td>
								<div class="dropdown">
									<button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
									aria-expanded="false">
										الأعدادات
									</button>
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<a class="dropdown-item" href="{{route('terms.edit', $term->id)}}">تعديل</a>
										<a class="dropdown-item" data-toggle="modal" href="#myModal-{{ $term->id }}">حذف</a>
									</div>
								</div>

								<div class="modal fade" id="myModal-{{ $term->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
								<div class="modal-dialog">
								<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title">حذف الشروط</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
								<form role="form" action="{{ url('admin/terms/'.$term->id) }}" class="" method="POST">
								<input name="_method" type="hidden" value="DELETE">
								{{ csrf_field() }}
								<p>هل أنت متأكد من الحذف ؟</p>
								<button type="submit" class="btn btn-danger" name='delete_modal'>حذف</button>
								<button type="button" class="btn btn-success" data-dismiss="modal">الغاء</button>
								</form>
								</div>
								</div>
								</div>
								</div>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
        </div>
	</div>
</div>
@endsection